name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack-server:7.0.6-RC9
        env:
          REDIS_ARGS: "--requirepass ${{ secrets.REDIS_PASSWORD }} --user ${{ secrets.REDIS_USER }} on >${{ secrets.REDIS_PASSWORD}} allkeys allcommands --user default off nopass nocommands"
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Feed redis scripts
        run: |
          sudo apt-get install libpq-dev -y
          SKIP_DOCKER=true ./scripts/run_redis.sh
      - name: Run tests
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack-server:7.0.6-RC9
        env:
          REDIS_ARGS: "--requirepass ${{ secrets.REDIS_PASSWORD }} --user ${{ secrets.REDIS_USER }} on >${{ secrets.REDIS_PASSWORD}} allkeys allcommands --user default off nopass nocommands"
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Feed redis scripts
        run: |
          sudo apt-get install libpq-dev -y
          SKIP_DOCKER=true ./scripts/run_redis.sh
      - name: Linting
        run: cargo clippy -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack-server:7.0.6-RC9
        env:
          REDIS_ARGS: "--requirepass ${{ secrets.REDIS_PASSWORD }} --user ${{ secrets.REDIS_USER }} on >${{ secrets.REDIS_PASSWORD}} allkeys allcommands --user default off nopass nocommands"
        ports:
          - 6379:6379
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install libpq
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - uses: Swatinem/rust-cache@v2
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Feed redis scripts
        run: SKIP_DOCKER=true ./scripts/run_redis.sh
      - name: Generate code coverage
        run: cargo tarpaulin --verbose --workspace